### ISSUE TITLE
../../../gopkg.in/gorethink/gorethink.v4/connection_handshake.go:17:2: cannot find package "golang.org/x/crypto/pbkdf2" in any of:

### ISSUE THREAD

**Issue by perfmeta** [openatx/atx-server#1]
日志：
liyudeMacBook-Pro:atx-server liyu$ go build
../../../gopkg.in/gorethink/gorethink.v4/connection_handshake.go:17:2: cannot find package "golang.org/x/crypto/pbkdf2" in any of:
	/usr/local/go/src/golang.org/x/crypto/pbkdf2 (from $GOROOT)
	/Users/liyu/go/src/golang.org/x/crypto/pbkdf2 (from $GOPATH)
../../sirupsen/logrus/terminal_check_notappengine.go:9:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
	/usr/local/go/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
	/Users/liyu/go/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)
../../cenkalti/backoff/context.go:6:2: cannot find package "golang.org/x/net/context" in any of:
	/usr/local/go/src/golang.org/x/net/context (from $GOROOT)
	/Users/liyu/go/src/golang.org/x/net/context (from $GOPATH)
../../sirupsen/logrus/terminal_bsd.go:6:8: cannot find package "golang.org/x/sys/unix" in any of:
	/usr/local/go/src/golang.org/x/sys/unix (from $GOROOT)
	/Users/liyu/go/src/golang.org/x/sys/unix (from $GOPATH)
liyudeMacBook-Pro:atx-server liyu$

**Comment by codeskyblue** [comment]
先 `go get`
