### ISSUE TITLE
执行go get -v github.com/openatx/atx-server报错

### ISSUE THREAD

**Issue by loneyao** [openatx/atx-server#13]
C:\Users\Administrator>go get -v github.com/openatx/atx-server
github.com/openatx/atx-server
# github.com/openatx/atx-server
go\src\github.com\openatx\atx-server\httpserver.go:397:5: hbs.OnReconnect undefi
ned (type *heartbeat.Server has no field or method OnReconnect)

**Comment by codeskyblue** [comment]
`go get -u -v`
