### ISSUE TITLE
执行uiautomator脚本失败

### ISSUE THREAD

**Issue by sunguangran** [openatx/atx-server#19]
![image](https://user-images.githubusercontent.com/2403503/42017387-69989ffe-7ae1-11e8-8776-a525b9c9ee94.png)
执行uiautomator脚本一直提示连不上uiautomator，其他功能都正常~

补充下：
小米手机正常的，坚果pro2 不好使

**Comment by codeskyblue** [comment]
可能init得时候，没有安装完

**Comment by HakunamatataLeo** [comment]
请问平台如何删除设备 @codeskyblue
