### ISSUE TITLE
连接设备操作后设备状态未变

### ISSUE THREAD

**Issue by hxbjava** [openatx/atx-server#2]
连接设备操作后设备状态未变，导致第二个人也连接就会看到全是黑的，无法操作。

**Comment by codeskyblue** [comment]
就是第一个人能用吗？

**Comment by laujay2000** [comment]
确实，在手机上点击停止ATxagENT后怎么开启呢，重启后网页上的状态一直是离线状态。

**Comment by codeskyblue** [comment]
手机上点击atx-agent后就只能重新用 `python -muiautomator2 init`开启了，别无他法

**Comment by laujay2000** [comment]
控制台上手机一直显示不出来

**Comment by codeskyblue** [comment]
啥控制台？

**Comment by codeskyblue** [comment]
如没有后续的回复 两天后关闭
