### ISSUE TITLE
网页的手机适配

### ISSUE THREAD

**Issue by Wang-Blue** [openatx/atx-server#20]
想在uiautomator.apk上加一个控制另外一台手机的功能，实现手机上操控另外一台手机。
但是发现手机上的chrome没法上下左右滑动，只能点击。
希望能加个滑动事件。。
![qq 20180628190308](https://user-images.githubusercontent.com/12178859/42030598-ecfe069e-7b05-11e8-94bd-cb29c42fb5b3.png)

**Comment by codeskyblue** [comment]
手机不太好操作吧

**Comment by Wang-Blue** [comment]
主要是APP的同事提到用鼠标滑动跟用手滑动感觉不一样，所以才打算做个手机上操作的。在上面的页面把屏幕全屏了。

**Comment by Wang-Blue** [comment]
@codeskyblue刚刚试了stf，是可以在手机浏览器上操作其他手机的

**Comment by codeskyblue** [comment]
恩，这个我知道，1是感觉手机访问起来不流畅 2是手机比较小访问起来也不方便，所以没加这块功能

**Comment by Wang-Blue** [comment]
@codeskyblue 方便帮忙加一下这个功能吗，或者可以告诉我是在哪个代码库修改的吗。因为同事有这个需求，想先试试，不行的话再说。

**Comment by codeskyblue** [comment]
github.com/openatx/atx-server

**Comment by Wang-Blue** [comment]
好的，我先试试

**Comment by Wang-Blue** [comment]
@codeskyblue 在stf找到了源代码，但是不知道怎么迁移到atx-server上来，求更新。

**Comment by codeskyblue** [comment]
虽然知道你的需求很迫切，不过我最近没什么时间。需要修改代码的话，应该是改这里 https://github.com/openatx/atx-server/blob/master/assets/remote.js#L661

**Comment by Wang-Blue** [comment]
那我再试试，谢谢
