### ISSUE TITLE
远程唤醒功能实现

### ISSUE THREAD

**Issue by numbqq** [openatx/atx-server#22]
我想在控制页面增加一个远程唤醒的功能，如[WOL(Wake On Lan)](https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%B7%AF%E5%96%9A%E9%86%92)，但是要实现这个功能需要发送UDP广播，我对前端不是太了解，想请问下有没有什么方式可以实现在控制页面发送UDP广播呢？谢谢！

**Comment by numbqq** [comment]
这个功能我这边已经有一个简单的实现了：
https://github.com/numbqq/atx-server/commit/4f588374633802f57406781950ff1a4c0749d3f7

https://github.com/numbqq/atx-server/commit/689ebf4cb8937a383764dd04cda30100687a2599

**Comment by codeskyblue** [comment]
wakeup  应该是keyevent POWER吧

**Comment by numbqq** [comment]
不是的，这个poweroff后整个系统都断电了的，不是休眠状态，只有以太网部分还在上电工作，所有收到WOL的包后以太网的一个中断脚会控制系统电源唤醒。这个只是一个特殊的需求，一般不会用到，像手机等都没有这个的。

**Comment by codeskyblue** [comment]
刚没怎么仔细看，发现你这个代码写的不错呀
