### ISSUE TITLE
[Need Help]Can not figure out how the device info is updated by closing the remote tab

### ISSUE THREAD

**Issue by yanqian** [openatx/atx-server#27]
Hi sir, 
 I am reading the code. Got into some confuse, could u kindly help me?

 https://github.com/openatx/atx-server/blob/master/templates/remote.html#L70
 When close a tab, the device is auto released. And using filed in the device info is updated in db, then the index page can update the device using status.
Here what I don't understand is I don't see any release api called when closing the tab, how is the using filed updated.

Thanks.

**Comment by codeskyblue** [comment]
websocket

**Comment by yanqian** [comment]
Actually I know there is a websocket in index page which monitor the device info change. I do not understand how it interact with the remote page?
