### ISSUE TITLE
为什么注册到服务器上的ip是docker容器网关的ip而不是手机的真实IP？

### ISSUE THREAD

**Issue by IvyBF** [openatx/atx-server#28]
用docker-compose构建好容器环境，然后使用命令：
`python  -m   uiautomator2  init   atxserver-addr`将手机注册到服务器上。
设备列表显示的不是手机的真实ip而是docker容器的网关IP

**Comment by codeskyblue** [comment]
还不支持，等待支持中

**Comment by ztiandan** [comment]
我也有这个问题，docker-compose启动后发现ip显示的不太对是docker网关ip，这个问题有修复方法吗？

**Comment by mingyuan-xia** [comment]
对，这个是docker后遇到的一个技术问题，正在调研解决，原因是用了docker后，其实是用iptable把物理网卡入口流量重定向到docker虚拟网卡的container，这样就影响了ip，变成了docker虚拟网卡的网段

欢迎讨论方案

**Comment by jerrylizilong** [comment]
尝试直接在  docker  的rethinkdb 里加一个设备， 是可以正常调起测试的， 所以感觉现在只是卡在设备注册到  atx server 这一步。

能否考虑从 uiautomator2 里修改， 注册到  atxserver 的时候把当前设备的 ip 作为一个参数传过去，而不是直接从请求里获取？这样是否可以避免重定向导致 ip 不正确的问题？

**Comment by jerrylizilong** [comment]
这个问题好像已经解决了？
我使用最新的  uiautomator2 库在设备上安装， 可以正确注册到  docker 中的 atxserver ， 而且可以正确调用和执行用例了

**Comment by codeskyblue** [comment]
docker用--net host 模式是可以的，不过我真的还没有解决这个问题

**Comment by mingyuan-xia** [comment]
他的截图里好像是docker网卡 但是通了很奇怪
