### ISSUE TITLE
连接设备后，管理界面无法操控

### ISSUE THREAD

**Issue by jphtmt** [openatx/atx-server#3]
![image](https://user-images.githubusercontent.com/16203408/34814928-6ff66140-f6ea-11e7-988b-b0ba14a3c283.png)
![image](https://user-images.githubusercontent.com/16203408/34814948-7dc3d870-f6ea-11e7-8f92-e9bfbc260e08.png)
![image](https://user-images.githubusercontent.com/16203408/34814963-8551ed66-f6ea-11e7-9950-5fdc66291a33.png)
通过```curl -X POST $SERVER_URL/devices/{query}/reserved 命令返回success```，但是管理界面无法勾选

**Comment by codeskyblue** [comment]
设备离线了，操作不了很正常

**Comment by jphtmt** [comment]
如何看出设备已经离线，我设备没有关机，且uiautomator 显示 is running

**Comment by codeskyblue** [comment]
atx-agent与atx-server是通过wifi连接的，如果手机的wifi断开了（有可能是锁屏之后，手机自己断开wifi了）就会导致设备离线

**Comment by codeskyblue** [comment]
如没有后续的回复 两天后关闭
