### ISSUE TITLE
atx-server管理的在线设备和离线设备检测不准确，或者没有在线与否的标志位

### ISSUE THREAD

**Issue by 1281480917** [openatx/atx-server#31]
按照下图方法获取atx-server管理的在线ip
![image](https://user-images.githubusercontent.com/16160664/47472483-7f98e300-d841-11e8-9502-02835439a5d0.png)
![image](https://user-images.githubusercontent.com/16160664/47472505-8c1d3b80-d841-11e8-8ec8-192e0618c220.png)
用如图所示的present 属性判断设备是否在线，测试的三部手机,都曾经上过线，在atx-server里有记录，然后一部手机关机，一部掉线，一部在线，但是这个标志位一直都为True,然后测试代码跑起来自然连接不上其他两部不在线的手机，报拒绝访问的错误，控制台只显示在线手机online，其他两部掉线手机控制台没任何信息输出，web管理界面有三部手机信息

**Comment by mingyuan-xia** [comment]
管理方式是heartbeat，活着的会向server报告，超过几次heartbeat没有反应的认为死了；可以考虑增加一个刷新按钮，向所有设备ping更新present状态
