### ISSUE TITLE
windows下获取不到设备列表

### ISSUE THREAD

**Issue by zhaiworld** [openatx/atx-server#32]
server也起来了，init也成功了 ，网络也能ping通的 ，杀毒软件 防火墙之类的也关了，手机上允许USB模拟权限开启了，更换过一台设备但是网页上还是没有出现设备。
`$ curl 127.0.0.1:8000/list
null`
PC：windows 10
手机：小米5s\红米note5
![image](https://user-images.githubusercontent.com/4532011/47541808-462da980-d90d-11e8-97f2-a92419ece2f9.png)
请老师帮忙分析一下原因，另外，文档中提到的API，我从哪里可以看到并编辑呢？
`$ curl $SERVER_URL/list
[
    {
        "udid": "741AEDR42P6YM-2c:57:31:4b:40:74-M2_E",
        "ip": "10.240.218.20",
        "present": true,
        "ready": true,
        "using": true,
        "provider": null,
        "serial": "741AEDR42P6YM",
        "brand": "Meizu",
        "model": "M2 E",
        "hwaddr": "2c:57:31:4b:40:74",
        "agentVersion": "0.1.1",
        "battery": {},
        "display": {
            "width": 1080,
            "height": 1920
        }
    }
]`

**Comment by mingyuan-xia** [comment]
你这个是rethinkdb的界面，不是atx-server的界面，你 `127.0.0.1:8000`是rethinkdb还是atx-server?
