### ISSUE TITLE
atx-server每次重新启动建议把数据库中presen字段默认全部置为false

### ISSUE THREAD

**Issue by 1281480917** [openatx/atx-server#33]
在atx-server服务关闭时，已经在线的设备有可能掉线，消息无法发送到服务器数据库中。当atx-server服务再次开启时，数据库中presen仍然为True，其实设备已经掉线，这样会导致连接设备测试时出错，因此建议atx-server每次重新启动建议把数据库中presen字段默认全部置为false
![image](https://user-images.githubusercontent.com/16160664/47565363-c0d0e600-d95a-11e8-8549-3f9466eecbee.png)

**Comment by mingyuan-xia** [comment]
有道理，欢迎PR

**Comment by 1281480917** [comment]
这个数据库似乎被修改了登陆账户和密码，我只能在web段访问，代码里登陆不了

**Comment by mingyuan-xia** [comment]
你看下database.go

**Comment by 1281480917** [comment]
func initDB(address, dbName string) {
	r.SetTags("gorethink", "json")
	r.SetVerbose(true)
	session, err := r.Connect(r.ConnectOpts{
		Address:    address,
		Database:   dbName,
		InitialCap: 1,
		MaxOpen:    10,
	})
r.Table("devices").Update(map[string]interface{}{
		"present":     false,
		"using":       false,
		"provider_id": 0,
	}).Exec(session)
atx-server初始化的时候貌似已经把present置为false了，但是貌似WiFi连接并没有起到效果。连接数据库似乎不需要特别设置用户名密码和其他特殊参数
