### ISSUE TITLE
Lenovo P1c58手机 - remote操作手机应用无效

### ISSUE THREAD

**Issue by hswyxj** [openatx/atx-server#34]
## Issue and steps to reproduce (复现步骤)
联想P1C58 - 使用remote操作手机应用无效（点击+滑动）

- 手机型号： Lenovo P1c58（系统版本：6.0.1(23)）

## Screenshots （相关截图）
![debugx5](https://user-images.githubusercontent.com/28854143/49625904-5bb8e780-fa12-11e8-810b-c96817afb22d.gif)

**Comment by mingyuan-xia** [comment]
`adb shell getevent -lt` 输出贴一下

**Comment by hswyxj** [comment]
**adb shell getevent -lt 输出如下：**

[   11282.121032] /dev/input/event5: EV_SYN       0005                 07289756

[   11282.121032] /dev/input/event5: EV_SYN       SYN_REPORT           00000000

[   11282.191082] /dev/input/event5: EV_ABS       ABS_X                00000028

[   11282.191082] /dev/input/event5: EV_ABS       ABS_Z                00000405

[   11282.191082] /dev/input/event5: EV_SYN       0004                 00002c12

[   11282.191082] /dev/input/event5: EV_SYN       0005                 0b543168

[   11282.191082] /dev/input/event5: EV_SYN       SYN_REPORT           00000000

[   11282.260970] /dev/input/event5: EV_ABS       ABS_X                00000024

[   11282.260970] /dev/input/event5: EV_ABS       ABS_Z                00000401

[   11282.260970] /dev/input/event5: EV_SYN       0004                 00002c12

[   11282.260970] /dev/input/event5: EV_SYN       0005                 0f7ff1ee

[   11282.260970] /dev/input/event5: EV_SYN       SYN_REPORT           00000000

[   11282.330989] /dev/input/event5: EV_ABS       ABS_X                00000027

[   11282.330989] /dev/input/event5: EV_ABS       ABS_Y                ffffffdb

[   11282.330989] /dev/input/event5: EV_ABS       ABS_Z                00000404

[   11282.330989] /dev/input/event5: EV_SYN       0004                 00002c12

**Comment by mingyuan-xia** [comment]
这个设备好诡异，正常的都是ABS_X ABS_Y作为屏幕XY
这个是X和Z从来没有见过这种设备，而且Y还是一个很大的负数 ffffffdb
这个无法支持，底层使用的是 minitouch
换设备吧
