### ISSUE TITLE
atx-server重构计划

### ISSUE THREAD

**Issue by codeskyblue** [openatx/atx-server#39]
- [x] 使用Python3重写（用来降低开发和维护难度）
- [ ] WOL的支持 ref: https://github.com/openatx/atx-server/issues/22
- [ ] 同时支持USB设备和WIFI设备
- [x] 支持`adb connect`
- [x] 支持登录认证
- [ ] 显示每台设备的使用率
- [ ] 支持多机同时控制 （多设备控制的控制可以将功能简化下，只保留点击和滑动）
- [ ] 心跳协议使用websocket或者UDP，放弃原来的HTTP (这里的实现需要注意下 websocket重连的问题）
- [ ] 支持跨网段的设备连接（比如家里的设备）
- [ ] 页面元素解析

新项目地址：https://github.com/openatx/atxserver2

**Comment by IvyBF** [comment]
有考虑把页面元素解析的功能也一起集成进来么

**Comment by thinkhy** [comment]
@codeskyblue 比较好奇Python3重写server的具体收益？用golang在维护和部署方面可能还更简单，逃~

**Comment by codeskyblue** [comment]
@thinkhy 实践感觉python3比go更适合写web 另外很多人不熟悉go 修改起来难度比较大

**Comment by wyhwow** [comment]
有哪些模块化的东西可以分出来吗，最近在做这方面的东西，或许可以帮上一点忙

**Comment by codeskyblue** [comment]
@wyhwow 先说说你可以帮上哪些忙呀

**Comment by wyhwow** [comment]
@codeskyblue 上面的列的那些页面元素解析应该可以的，最近在使用django开发东西，还在看atx-server的的内容，其他具体的内容可能要详细聊

**Comment by codeskyblue** [comment]
重构项目用的是Tornado ，不过参考了django的一些目录结构。数据库还是用的rethinkdb
