### ISSUE TITLE
设备断开wifi之后，atx-server仍然显示设备在线，怎么清除不在线的设备

### ISSUE THREAD

**Issue by ejenna** [openatx/atx-server#40]
1、atx-server绑定的ip变化之后，之前平台上的设备仍然存在并且可以操作，为什么不需要重新绑定到新的IP地址？
2、设备因为电量不足自动关机，但是atx-server上仍然显示这些设备在线，present 仍然显示为True，怎么将这些设备清除，正确显示在线的设备？

**Comment by codeskyblue** [comment]
atx-server最新了？

**Comment by ejenna** [comment]
最新了，我重启了服务，不在线的设备已经没有了

**Comment by ejenna** [comment]
这个问题有答案吗？
1、atx-server绑定的ip变化之后，之前平台上的设备仍然存在并且可以操作，为什么不需要重新绑定到新的IP地址？
