### ISSUE TITLE
设备ip显示有误，无法显示手机

### ISSUE THREAD

**Issue by lycfr** [openatx/atx-server#41]
ATX-server部署好后，设备连接上，发现设备ip地址有误
![image](https://user-images.githubusercontent.com/29672247/51524413-f8233600-1e68-11e9-8af5-cc2b8efe381e.png)
![image](https://user-images.githubusercontent.com/29672247/51524448-06715200-1e69-11e9-8604-7372ccc961d7.png)
![image](https://user-images.githubusercontent.com/29672247/51524462-112be700-1e69-11e9-82d3-704dd5f26c68.png)

我这是哪里没部署好还是有bug

**Comment by codeskyblue** [comment]
感觉docker搭建的？目前还支持 --net=host的模式启动。 这个问题，暂时放到重构版里处理了
