### ISSUE TITLE
ATX-Server 管理页面不能打开

### ISSUE THREAD

**Issue by echo557** [openatx/atx-server#42]
上周搭建好环境的时候，server 页面还能加载，今天就完全不行了。 运行报错：
\atx-server.exe --port 8060

 运行看到有打印信息：
        C:/Go/src/net/http/server.go:1847 +0x64d
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2851 +0x2fc
2019/01/22 17:27:47 http: panic serving [::1]:4585: html/template: pattern matches no files: `templates/*.html`
goroutine 61 [running]:
net/http.(*conn).serve.func1(0xc000164500)
        C:/Go/src/net/http/server.go:1746 +0xd7

看了是找不到html 文件，有去文件下检查，的确也没有，这个改如何解决呢？

**Comment by echo557** [comment]
> 上周搭建好环境的时候，server 页面还能加载，今天就完全不行了。 运行报错：
> \atx-server.exe --port 8060
> 
> 运行看到有打印信息：
> C:/Go/src/net/http/server.go:1847 +0x64d
> created by net/http.(*Server).Serve
> C:/Go/src/net/http/server.go:2851 +0x2fc
> 2019/01/22 17:27:47 http: panic serving [::1]:4585: html/template: pattern matches no files: `templates/*.html`
> goroutine 61 [running]:
> net/http.(*conn).serve.func1(0xc000164500)
> C:/Go/src/net/http/server.go:1746 +0xd7
> 
> 看了是找不到html 文件，有去文件下检查，的确也没有，这个改如何解决呢？

图片显示
该网页无法正常运作 localhost 未发送任何数据。
ERR_EMPTY_RESPONSE

**Comment by codeskyblue** [comment]
atx-server运行要在templates同一层级的目录下
