### ISSUE TITLE
手机重启后如何，如何启动uiautomator和atx-agent

### ISSUE THREAD

**Issue by HakunamatataLeo** [openatx/atx-server#5]
我的手机重启后，打开uiautomator的app，通过浏览器打开链接也连接不上机器，是不是需要adb在哪个目录下重启下手机里的服务？

**Comment by codeskyblue** [comment]
手机重启后必须重新 init 操作

**Comment by ldienw** [comment]
重新打开app为什么启动不了服务的？

**Comment by codeskyblue** [comment]
其中依赖的atx-agent需要连接USB线，使用开发者权限才能开启
