### ISSUE TITLE
一个小问题？

### ISSUE THREAD

**Issue by bsshanghai** [openatx/atx-server#6]
![image](https://user-images.githubusercontent.com/28524371/37815886-c1f8f36a-2eab-11e8-9afb-2de6fc829a67.png)

点击锁屏的话，虽然下面只勾选了1号，但是其他的也都跟着黑屏了。

**Comment by codeskyblue** [comment]
@这一栏用于区分设备是否可以自动化。刚开始的时候都是不选中的。
改成这种了，免得你理解错
![image](https://user-images.githubusercontent.com/3281689/37824180-c1f81024-2ec6-11e8-9070-b571d772fabf.png)

现在还不支持选择设备进行批量操作
