### ISSUE TITLE
go build 缺失文件

### ISSUE THREAD

**Issue by HakunamatataLeo** [openatx/atx-server#7]
![image](https://user-images.githubusercontent.com/4550421/38532552-f3caaeec-3ca7-11e8-9410-da28c1305c5a.png)

**Comment by codeskyblue** [comment]
先 go get 呀，先看看go的基础在搞

**Comment by HakunamatataLeo** [comment]
我知道原因了，之前go get 过，这次忘记 go get -v -u xxx了
